{"name": "test_case_3_sin", "status": "failed", "statusDetails": {"message": "AssertionError: Подсчет неверен\nassert '0' == 'Error'\n  - Error\n  + 0", "trace": "self = <test_calc.TestSuite object at 0x00000192AF8C33A0>\nconfig_browser = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"021c9a62524561cd3df145b526f652d5\")>\n\n    def test_case_3_sin(self, config_browser):\n        page = Worker(config_browser)\n        page.go_to_site('http://google.com')\n        page.enter_word('Калькулятор')\n        page.click_on_the_search_button()\n        page.expression_input('sin()')\n        page.click_count_button()\n        sleep(0.5)\n        result = page.check_result()\n>       assert '0' == result, 'Подсчет неверен'\nE       AssertionError: Подсчет неверен\nE       assert '0' == 'Error'\nE         - Error\nE         + 0\n\ntest_calc.py:115: AssertionError"}, "start": 1633897072408, "stop": 1633897074995, "uuid": "443dc5b9-60cc-4fdc-8535-3492ef962371", "historyId": "5a6d951aa85440c17e94b918b37d4bd4", "testCaseId": "4865149f04d595e3d00b4631ed5d9f83", "fullName": "test_calc.TestSuite#test_case_3_sin", "labels": [{"name": "suite", "value": "test_calc"}, {"name": "subSuite", "value": "TestSuite"}, {"name": "host", "value": "DESKTOP-LD7CAVE"}, {"name": "thread", "value": "17012-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_calc"}]}